Finally fixed issues with recursive list

diff --git a/initramfs/bin/ls b/initramfs/bin/ls
--- a/initramfs/bin/ls
+++ b/initramfs/bin/ls
@@ -1,4 +1,4 @@
-#!/bin/dash
+#!/bin/dash 
 ##############################################################################
 # Copyright (c) 2012 Mark Charlebois
 # 
@@ -20,108 +20,159 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 ##############################################################################
-dir=`dirname $0`
-pwd=`pwd`
-cd $dir
-cmd=`pwd`/`basename $0`
-cd $pwd
-
-flags=""
-list=""
-num=0
-for k in $*
-do
-	case $k in
-	-R)
-		flag_R=1;
-		;;
-	-1)
-		flag_1=1;
-		;;
-	-F)
-		flag_F=1;
-		;;
-	-z)
-		flag_z=1;
-		;;
-	-*)
-		echo "Usage $0 -[RF1] [file...]"
-		exit 1
-		;;
-	*)
-		if [ -e "$k" ]; then
-			if [ -n "$list" ]; then
-				num=2
-			else
-				num=1
-			fi
-			list=${list}" $k"
-			continue
-		else
-			echo "ls: cannot access ${k}: No such file or directory"
-			exit 1
-		fi
-		;;
-	esac
-	flags=${flags}" $k"
-done
-if [ -z "$list" ]; then
-	if [ -n "$flag_R" ]; then
-		list="."
-	else
-		list="."
-	fi
-fi
-flist=""
-for k in $list
-do
-if [ -d $k ]; then 
-	if [ -n "$flag_R" -o -z "$flag_z" ]; then
-		dlist=${dlist}" $k"
-	fi
-	if [ -n "$flag_z" ]; then
-		if [ -n "$flag_F" ]; then
-			flist=${flist}"$k/  "
-		else 
-			flist=${flist}"$k  "
-		fi
-	fi
-	dirs=1
-else
-	if [ -n "$flag_F" -a -L "$k" ]; then
-		flist=${flist}"${k}@  "
-	elif [ -n "$flag_F" -a -x "$k" ]; then
-		flist=${flist}"${k}*  "
-	else
-		flist=${flist}"$k  "
-	fi
-fi
-done
-if [ -z "$flist" -a -z "$dirs" ]; then 
-	$cmd $flags *
-elif [ "" != "$flist" ]; then
-	if [ -z "$flag_1" ]; then
-		echo "$flist"
-	else
-	for k in $flist
-	do
-		echo $k
-	done
-	fi
-fi
-for d in $dlist
-do
+get_commandname() {
+	dir=`dirname $1`
 	pwd=`pwd`
-	cd $d
-	if [ -n $flags_z ]; then
-		echo
-		echo ${d}:
-	else
-		$flags=${flags}" -z"
-	fi
-	if [ "`echo *`" != "*" ]; then
-		$cmd $flags *
-	fi
+	cd $dir
+	cmd=`pwd`/`basename $1`
 	cd $pwd
-done
+}
 
+parse_args() {
+	flags=""
+	list=""
+	dlist=""
+	num=0
+	for k in $*
+	do
+		case $k in
+		-R)
+			flag_R=1;
+			;;
+		-1)
+			flag_1=1;
+			;;
+		-F)
+			flag_F=1;
+			;;
+		-z)
+			flag_z=1;
+			;;
+		-*)
+			echo "Usage $0 -[RF1] [file...]"
+			exit 1
+			;;
+		*)
+			if [ -e "$k" ]; then
+				if [ -d $k ]; then
+					if [ -n "$dlist" ]; then
+						num=2
+					else
+						num=1
+					fi
+					dlist=${dlist}" $k"
+					list=${list}" $k"
+				else
+					list=${list}" $k"
+				fi
+				continue
+			else
+				echo "ls: cannot access ${k}: No such file or directory"
+				exit 1
+			fi
+			;;
+		esac
+		flags=${flags}" $k"
+	done
+}
+
+
+handle_special_cases() {
+	# Do not traverse dirs if z flag is set
+	if [ -n "$flag_z" ]; then
+		dlist=""
+	#if no files/dirs provided list current dir
+	elif [ -z "$list" ]; then
+		if [ "`echo *`" != "*" ]; then
+			if [ -n "$flag_R" ]; then
+				$cmd $flags *
+			else
+				$cmd $flags -z *
+			fi
+		fi
+		exit 0
+	#if one dir provided, cd to there and list
+	elif [ $num -eq 1 -a "$list" = "$dlist" ]; then
+		pwd=`pwd`
+		cd $dlist
+		if [ "`echo *`" != "*" ]; then
+			if [ -n "$flag_R" ]; then
+				$cmd $flags *
+			else
+				$cmd $flags -z *
+			fi
+		fi
+		cd $pwd
+		exit 0
+	# Otherwise prune dirs from $list
+	else
+		tlist=$list
+		list=""
+		for t in $tlist
+		do
+			if [ ! -d $t ]; then
+				list=${list}$t" "
+			fi
+		done
+	fi
+}
+
+format_entry() {
+	entry="$1"
+	if [ -d $1 ]; then
+		entry="$1/"
+	elif [ -L "$1" ]; then
+		entry="${1}@"
+	elif [ -x "$1" ]; then
+		entry="$1\*"
+	fi
+}
+
+print_entries() {
+	flist=""
+	for f in $list
+	do
+		if [ -n "$flag_F" ]; then
+			format_entry $f
+		else
+			entry=$f
+		fi
+		flist=${flist}$entry" "
+	done
+	if [ -z "$flag_1" ]; then
+		for f in $flist
+		do
+			echo -n $f
+			echo -n "  "
+		done
+		echo
+	else
+		for f in $flist
+		do
+			echo $f
+		done
+	fi
+}
+
+process_subdirs() {
+	if [ -z "$flag_z" ]; then
+		if [ -z "$flag_R" ]; then
+			flags=${flags}" -z"
+		fi
+	fi
+	for d in $dlist
+	do
+		echo
+		echo $d:
+		pwd=`pwd`
+		cd $d
+		$cmd $flags 
+		cd $pwd
+	done
+}
+
+get_commandname $0
+parse_args $*
+handle_special_cases
+print_entries
+process_subdirs
